CinéBuddy/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CinéBuddy.Models.Types;
using CinéBuddy.Models;

namespace CinéBuddy.Controllers
{
    public class LogInController : Controller
    {
        Films model = new Films();
        

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login(string username, string password)
        {
            if (model.CheckCredentials(username, password))
            {
                Session["User"] = model.GetUserByUserName(username);
                Session["Username"] = username;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                Response.Write("<script>alert('Inloggegevens zijn onjuist.');</script>");
                return View("Index");
            }
        }
    }
}

CinéBuddy/Controllers/SneakPreviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CinéBuddy.Models;
using System.Web.Mvc;

namespace CinéBuddy.Controllers
{
    public class SneakPreviewController : Controller
    {
        Films model = new Films();
        // GET: SneakPreview
        public ActionResult Index()
        {
            ViewBag.Film = model.haalSneakPreviewOp();
            ViewBag.User = model.returnHuidigeGebruiker(); 
            return View();
        }
    }
}

CinéBuddy/Views/Shared/_Layout.cshtml
@using CinéBuddy.Models.Types;
@{
    Gebruiker gebruiker = (Gebruiker)HttpContext.Current.Session["user"];
    Admin admin = (Admin)HttpContext.Current.Session["admin"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <a class="navbar-brand" style="color:yellow">CinéBuddy</a>
            <div class="navbar-collapse collapse">
                @if (gebruiker != null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Films", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Sneak Preview", "Index", "SneakPreview", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Gold abonnement", "Index", "Gold", new { area = "" }, new { @class = "navbar-brand" })</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Index", "Profile")" class="navbar-brand"><span class="glyphicon glyphicon-user"></span> @gebruiker.gebruikersNaam</a></li>
                        <li><a href="@Url.Action("Logout", "Home")" class="navbar-brand"><span class="glyphicon glyphicon-log-out"></span> Uitloggen</a></li>
                    </ul>
                }
                @if (admin != null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Films", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Sneak Preview", "Index", "SneakPreview", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Gold abonnement", "Index", "Gold", new { area = "" }, new { @class = "navbar-brand" })</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Index", "Profile")" class="navbar-brand"><span class="glyphicon glyphicon-user"></span> @admin.gebruikersNaam</a></li>
                        <li><a href="@Url.Action("Logout", "Home")" class="navbar-brand"><span class="glyphicon glyphicon-log-out"></span> Uitloggen</a></li>
                    </ul>
                }
                @if (gebruiker == null && admin == null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Films", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Sneak Preview", "Index", "SneakPreview", new { area = "" }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Gold abonnement", "Index", "Gold", new { area = "" }, new { @class = "navbar-brand" })</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Index", "LogIn")" class="navbar-brand"><span class="glyphicon glyphicon-log-in"></span> Inloggen</a></li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>